from __future__ import annotations

import subprocess
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "generate-hub-pages"


class HubPagesTests(unittest.TestCase):
    def test_canonical_docs_generate_marked_starlight_pages(self) -> None:
        result = subprocess.run(["python3.11", str(SCRIPT)], cwd=ROOT, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)
        page = ROOT / "docs-site/src/content/docs/hub/gui-dashboard.md"
        rendered = page.read_text(encoding="utf-8")
        self.assertIn("<!-- Generated by scripts/generate-hub-pages. Do not edit manually. -->", rendered)
        self.assertIn("В footer status dashboard", rendered)

    def test_llms_generation_refreshes_canonical_hub_pages(self) -> None:
        result = subprocess.run(["python3.11", str(ROOT / "scripts" / "generate-llms")], cwd=ROOT, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("Generated by scripts/generate-hub-pages", (ROOT / "docs-site/src/content/docs/standards/generated-artifacts.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
